/*
ROLLBACK --------------

1. remove all evidence of the premature computations that were performed (the events processed with timestamps greater than the timestamp of the straggler).  as part of this step, you need to:

    1.	find the last state saved with a timestamp before that of the straggler

    2.	coast forward to the straggler: in the coast forward phase, you are processing events in the input queue with timestamps between the saved state and the straggler 
    (basically what you are doing is rebuilding the state needed to process the straggler).  as you process these events, you do not retransmit the output events as they 
    were already correctly computed and transmitted (that is the coast forward step is only needed to rebuild the state).

    3.	send out anti-messages to retract any events that were prematurely generated when events with timestamps above the straggler were processed 
    (ideally you will do this as the first step during a rollback [as it helps to terminate the premature event processing as early as possible], but this
     might overly complicate your initial implementation; however if it's easy to make this the first step then do it that way).  
     you don't want to sent anti-message for all events in the output queue as some of those will be generated by events with timestamps earlier than the straggler 
     (and we cannot also discount the possibility that even later stragglers will arise with even earlier timestamps 
     (that is why we have to save everything forward of the current estimated GVT.

2.  return to normal event processor where the straggler and the undone events will ultimately be reprocessed by the normal event processing mechanisms.

*/

#include "Worker.hpp"

namespace warped {
    Worker::Worker() {}

    void Worker::initialize() 
    {
        
    }

    void Worker::coastForward(std::shared_ptr<Event> straggler_event, 
                                std::shared_ptr<Event> restored_state_event) {

        LogicalProcess* lp = lps_by_name_[straggler_event->receiverName()];
        unsigned int current_lp_id = local_lp_id_by_name_[straggler_event->receiverName()];

        auto events = event_set_->getEventsForCoastForward(current_lp_id, straggler_event,
            restored_state_event);

        // NOTE: events are in order from LARGEST to SMALLEST, so reprocess backwards
        for (auto event_riterator = events->rbegin();
                        event_riterator != events->rend(); event_riterator++) {

            assert(**event_riterator <= *straggler_event);

            // This just updates state, ignore new events
            lp->receiveEvent(**event_riterator);

            tw_stats_->upCount(COAST_FORWARDED_EVENTS, thread_id);

            // NOTE: Do not send any new events
            // NOTE: All coast forward events are already in processed queue, they were never removed.
        }
    }

    void Worker::rollback(std::shared_ptr<Event> straggler_event)
    {
        
        auto timestamp_straggler = event->timestamp()
        // find saved state in stateQ with the first timestamp before the timestamp of the straggler
        foreach state in stateQ () {
            if (state.timestamp < timestamp_straggler) {
                coastToPoint = timestamp
            }                
        }
        // coast forward
        auto restored_state_event = state_manager_->restoreState(straggler_event, local_lp_id,
            current_lp);
        assert(restored_state_event);
        assert(*restored_state_event < *straggler_event);
        
        coastForward(straggler_event, restored_state_event);
        // move pointer forward towards the timestamp before the straggler
        // send anti-messages using the records in the outQ and preserve the MPI_Isend pointer to the last message sent in outMessage
        auto events_to_cancel = output_manager_->rollback(straggler_event, local_lp_id);
        if (events_to_cancel != nullptr) {
            cancelEvents(std::move(events_to_cancel));
        }
        return;
        

        /*
        unsigned int local_lp_id = local_lp_id_by_name_[straggler_event->receiverName()];
        LogicalProcess* current_lp = lps_by_name_[straggler_event->receiverName()];

        // Statistics count
        if (straggler_event->event_type_ == EventType::POSITIVE) {
            tw_stats_->upCount(PRIMARY_ROLLBACKS, thread_id);
        } else {
            tw_stats_->upCount(SECONDARY_ROLLBACKS, thread_id);
        }

        // Rollback output file stream. XXX so far this is not used by any models
        twfs_manager_->rollback(straggler_event, local_lp_id);

        // We have major problems if we are rolling back past the GVT
        assert(straggler_event->timestamp() >= gvt_manager_->getGVT());

        // Move processed events larger  than straggler back to input queue.
        event_set_->acquireInputQueueLock(local_lp_id);
        event_set_->rollback(local_lp_id, straggler_event);
        event_set_->releaseInputQueueLock(local_lp_id);

        // Restore state by getting most recent saved state before the straggler and coast forwarding.
        auto restored_state_event = state_manager_->restoreState(straggler_event, local_lp_id,
            current_lp);
        assert(restored_state_event);
        assert(*restored_state_event < *straggler_event);

        // Send anti-messages
        auto events_to_cancel = output_manager_->rollback(straggler_event, local_lp_id);
        if (events_to_cancel != nullptr) {
            cancelEvents(std::move(events_to_cancel));
        }

        coastForward(straggler_event, restored_state_event);
        */
    }

    void Worker::processEvent(unsigned int id) // event here is a type, not an int
    {
        unsigned int thread_id = id;
        // Lock e.lp.inQ
        event_set_->acquireInputQueueLock(local_lp_id);

        // e <- e.lp.inQ.head()
        std::shared_ptr<Event> event = event_set_->getEvent(thread_id) // this needs to change

        // UnLock e.lp.inQ
        event_set_->releaseInputQueueLock(local_lp_id);

        if (event.type == ANTIMESSAGE) { // does ANTIMESSAGE = EventType::NEGATIVE
            // Find the positive message q that is the target of e
            if (q is in the processed queue) {
                rollback(q->prev);
            }
            // Remove q, e and refresh the LTSF queue for that LP
            return (NULL, NULL);
        }
        if (event.timestamp <= lvt) {
            rollback(event);
        }
        outEventList <- lp.eventExec(e) // should put a console log here to mark when an event is actually executed 
        // update LTSF entry for e.LP
        return (e, outEventList);

        /*
        thread_id = id;
        unsigned int local_gvt_flag;
        unsigned int gvt = 0;

        while (!termination_manager_->terminationStatus()) {
            // NOTE: local_gvt_flag must be obtained before getting the next event to avoid the
            //  "simultaneous reporting problem"
            local_gvt_flag = gvt_manager_->getLocalGVTFlag();

            std::shared_ptr<Event> event = event_set_->getEvent(thread_id);
            if (event != nullptr) {
                // If needed, report event for this thread so GVT can be calculated
                auto lowest_timestamp = event->timestamp();

    #ifdef PARTIALLY_SORTED_LADDER_QUEUE
                lowest_timestamp = event_set_->lowestTimestamp(thread_id);
    #endif

                gvt_manager_->reportThreadMin(lowest_timestamp, thread_id, local_gvt_flag);

                // Make sure that if this thread is currently seen as passive, we update it's state
                //  so we don't terminate early.
                if (termination_manager_->threadPassive(thread_id)) {
                    termination_manager_->setThreadActive(thread_id);
                }

                assert(comm_manager_->getNodeID(event->receiverName()) == comm_manager_->getID());
                unsigned int current_lp_id = local_lp_id_by_name_[event->receiverName()];
                LogicalProcess* current_lp = lps_by_name_[event->receiverName()];

                // Get the last processed event so we can check for a rollback
                auto last_processed_event = event_set_->lastProcessedEvent(current_lp_id);

                // The rules with event processing
                //      1. Negative events are given priority over positive events if they both exist
                //          in the lps input queue
                //      2. We assume that if we have a negative message, then we also have the positive
                //          message either in the input queue or in the processed queue. If the positive
                //          event is in the processed queue, then a rollback will occur and both events
                //          will end up in the input queue.
                //      3. When a negative event is taken from the schedule queue, it will be cancelled
                //          with it's corresponding negative message in the input queue. A rollback
                //          may occur first.
                //      4. When a positive event is taken from the schedule queue, it will always be
                //          processed. A rollback may occur first if it is a straggler.

                // A rollback can occur in two situations:
                //      1. We get an event that is strictly less than the last processed event.
                //      2. We get an event that is equal to the last processed event and is negative.

                if (last_processed_event &&
                        ((*event < *last_processed_event) ||
                            ((*event == *last_processed_event) &&
                            (event->event_type_ == EventType::NEGATIVE)))) {
                    rollback(event);
                }

                // Check to see if event is NEGATIVE and cancel
                if (event->event_type_ == EventType::NEGATIVE) {
                    event_set_->acquireInputQueueLock(current_lp_id);
                    bool found = event_set_->cancelEvent(current_lp_id, event);
                    event_set_->startScheduling(current_lp_id);
                    event_set_->releaseInputQueueLock(current_lp_id);

                    if (found) {
                        tw_stats_->upCount(CANCELLED_EVENTS, thread_id);
                    }
                    continue;
                }

                // process event and get new events
                auto new_events = current_lp->receiveEvent(*event);

                tw_stats_->upCount(EVENTS_PROCESSED, thread_id);

                // Save state
                state_manager_->saveState(event, current_lp_id, current_lp);

                // Send new events
                sendEvents(event, new_events, current_lp_id, current_lp);

                // Check for recent gvt update
                gvt = gvt_manager_->getGVT();
                if (gvt > current_lp->last_fossil_collect_gvt_) {
                    current_lp->last_fossil_collect_gvt_ = gvt;

                    // Fossil collect all queues for this lp
                    twfs_manager_->fossilCollect(gvt, current_lp_id);
                    output_manager_->fossilCollect(gvt, current_lp_id);

                    unsigned int event_fossil_collect_time =
                        state_manager_->fossilCollect(gvt, current_lp_id);

                    unsigned int num_committed =
                        event_set_->fossilCollect(event_fossil_collect_time, current_lp_id);

                    tw_stats_->upCount(EVENTS_COMMITTED, thread_id, num_committed);

                }

                // Move the next event from lp into the schedule queue
                // Also transfer old event to processed queue
                event_set_->acquireInputQueueLock(current_lp_id);
                event_set_->replenishScheduler(current_lp_id);
                event_set_->releaseInputQueueLock(current_lp_id);

            } else {
                // This thread no longer has anything to do because it's schedule queue is empty.
                if (!termination_manager_->threadPassive(thread_id)) {
                    termination_manager_->setThreadPassive(thread_id);
                }

                // We must have this so that the GVT calculations can continue with passive threads.
                // Just report infinite for a time.
                gvt_manager_->reportThreadMin((unsigned int)-1, thread_id, local_gvt_flag);
            }
        }
        */
    }

    void Worker::thread() 
    {
        /*
        while(!termination_manager_->terminationStatus()) {
            if (!(e<-ltsf.head()) || gvt.gvtEstCycle) {
                if (worker.outMessage != NULL) {
                    worker.outMessage.MPI_Wait()
                }
                gvt.barrier()
                gvt.barrier()
                e<-ltsf.refreshEvents(e)
                if (e != NULL) {
                    worker.gvtContrib<-e.timeStamp
                } else {
                    worker.gvtContrib<-+inf // fix 
                }
                gvt.barrier()
            }
            if (e != NULL) {
                for i <- 1, K0 {
                    for j <- 1, K1 {
                        outEventList <- processEvent(e)
                        for (outE in outEventList) {
                            if (outE.dest.LP is in LocalLPs) {
                                outE.dest.Lp.inQ.insert(outE)
                            }
                            else {
                                worker.outMessage = MPI_Isend(outE.dest.Lp)
                            }
                        }
                        if (!(e<-ltsf.head())) {
                            break;
                        }
                    }
                    if (!(e<- ltsf.refreshEvents(e))) {
                        break;
                    }
                }
            }
        }
        */
    }
}