/*
ROLLBACK --------------

1. remove all evidence of the premature computations that were performed (the events processed with timestamps greater than the timestamp of the straggler).  as part of this step, you need to:

    1.	find the last state saved with a timestamp before that of the straggler

    2.	coast forward to the straggler: in the coast forward phase, you are processing events in the input queue with timestamps between the saved state and the straggler 
    (basically what you are doing is rebuilding the state needed to process the straggler).  as you process these events, you do not retransmit the output events as they 
    were already correctly computed and transmitted (that is the coast forward step is only needed to rebuild the state).

    3.	send out anti-messages to retract any events that were prematurely generated when events with timestamps above the straggler were processed 
    (ideally you will do this as the first step during a rollback [as it helps to terminate the premature event processing as early as possible], but this
     might overly complicate your initial implementation; however if it's easy to make this the first step then do it that way).  
     you don't want to sent anti-message for all events in the output queue as some of those will be generated by events with timestamps earlier than the straggler 
     (and we cannot also discount the possibility that even later stragglers will arise with even earlier timestamps 
     (that is why we have to save everything forward of the current estimated GVT.

2.  return to normal event processor where the straggler and the undone events will ultimately be reprocessed by the normal event processing mechanisms.

*/

#include "Worker.hpp"

namespace warped {
    Worker::Worker() {}

    void Worker::initialize() 
    {
        
    }

    void Worker::rollback(int event)
    {
        timestamp_straggler = event.timestamp
        // find saved state in stateQ with the first timestamp before the timestamp of the straggler
        foreach state in stateQ () {
            if (state.timestamp < timestamp_straggler) {
                coastToPoint = timestamp
            }                
        }
        // coast forward
        // move pointer forward towards the timestamp before the straggler
        // send anti-messages using the records in the outQ and preserve the MPI_Isend pointer to the last message sent in outMessage
        //lastMessage = MPI_Isend Pointer
        foreach item in outQ () {
            // sendAntiMessage()
        }
        return;
    }

    void Worker::processEvent(int event) // event here is a type, not an int
    {
        // Lock e.lp.inQ
        // e <- e.lp.inQ.head()
        // UnLock e.lp.inQ
        if (e.type == ANTIMESSAGE) {
            // Find the positive message q that is the target of e
            if (q is in the processed queue) {
                rollback(q->prev);
            }
            // Remove q, e and refresh the LTSF queue for that LP
            return (NULL, NULL);
        }
        if (e.timestamp <= lvt) {
            rollback(e);
        }
        outEventList <- lp.eventExec(e) // should put a console log here to mark when an event is actually executed 
        // update LTSF entry for e.LP
        return (e, outEventList);
    }

    void Worker::thread() 
    {
        while(!termination_manager_->terminationStatus()) {
            if (!(e<-ltsf.head()) || gvt.gvtEstCycle) {
                if (worker.outMessage != NULL) {
                    worker.outMessage.MPI_Wait()
                }
                gvt.barrier()
                gvt.barrier()
                e<-ltsf.refreshEvents(e)
                if (e != NULL) {
                    worker.gvtContrib<-e.timeStamp
                } else {
                    worker.gvtContrib<-+inf // fix 
                }
                gvt.barrier()
            }
            if (e != NULL) {
                for i <- 1, K0 {
                    for j <- 1, K1 {
                        outEventList <- processEvent(e)
                        for (outE in outEventList) {
                            if (outE.dest.LP is in LocalLPs) {
                                outE.dest.Lp.inQ.insert(outE)
                            }
                            else {
                                worker.outMessage = MPI_Isend(outE.dest.Lp)
                            }
                        }
                        if (!(e<-ltsf.head())) {
                            break;
                        }
                    }
                    if (!(e<- ltsf.refreshEvents(e))) {
                        break;
                    }
                }
            }
        }
    }
}